* Git modes

GNU Emacs modes for Git-related files.


** Features

- =git-commit-mode= :: A GNU Emacs major mode for editing Git commit messages
     according to the [[http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html][guidelines by Tim Pope]], with optional [[http://magit.github.com/magit/][Magit]] integration.
- =gitconfig-mode= :: A ~conf-mode~-derived major mode for editing ~.gitconfig~
     files.


** Installation

Install the ELPA packages from [[http://melpa.milkbox.net][MELPA]] (bleeding edge snapshots) or [[http://marmalade-repo.org/][Marmalade]]
(stable releases) with ~M-x package-install git-commit-mode~ and/or ~M-x
package-install gitconfig-mode~, or [[https://github.com/lunaryorn/gitconfig-mode/tags][download]] the latest release and install
~git-commit-mode.el~ and/or ~gitconfig-mode.el~ with =M-x package-install-file=.

The modes are written and tested against GNU Emacs 24 and may or may not work in
earlier versions of GNU Emacs.


** Usage

*** =git-commit-mode=

Just configure ~emacs~ or ~emacsclient~ as editor for Git. =git-commit-mode=
will automatically be enabled for Git message buffers.

To enable integration with [[http://magit.github.com/magit/][Magit]] to provide font locking and auto filling to
=magit-log-edit-mode=, insert the following into your ~init.el~:

#+BEGIN_SRC emacs-lisp
  (add-hook 'magit-log-edit-mode-hook 'git-commit-mode-magit-setup)
#+END_SRC

*** =gitconfig-mode=

=gitconfig-mode= is automatically enabled for ~.gitconfig~ and ~.git/config~
files.  The mode is derived from =conf-unix-mode=, so all commands provided
by =conf-mode= (e.g. =conf-align-assignments=) will work as expected.

** Customization

- =git-commit-mode= :: ~M-x customize-group git-commit~
- =gitconfig-mode= :: No customization provided.


** Further help

- ~C-h f git-commit-mode~
- ~C-h f gitconfig-mode~


** Credits

=git-commit-mode= is forked of the [[https://github.com/rafl/git-commit-mode][original work]] by [[https://github.com/rafl][Florian Ragwitz]], improved by
[[https://github.com/jwiegley][John Wiegley]].  Thanks for their work.


** License

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 51 Franklin
Street, Fifth Floor, Boston, MA 02110-1301, USA.

See [[file:COPYING][COPYING]] for details.
